### ISSUE TITLE
TypeError: deprecate() got an unexpected keyword argument 'date'

### ISSUE THREAD

**Issue by erlfos** [ansible-collections/community.docker#141]
##### SUMMARY
I get error **TypeError: deprecate() got an unexpected keyword argument 'date'** when trying to use the module **docker_compose**. I have tried with both inline configuration copied from the examples in the docs, and my own docker-compose file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_compose
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/oss/ansible-soc/ansible.cfg
  configured module search path = ['/home/oss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]

pip_package_info:
    "output": {
        "changed": false,
        "failed": false,
        "packages": {
            "pip": {
                "docker": [
                    {
                        "name": "docker",
                        "source": "pip",
                        "version": "5.0.0"
                    }
                ],
                "docker-compose": [
                    {
                        "name": "docker-compose",
                        "source": "pip",
                        "version": "1.29.2"
                    }
                ],
                "dockerpty": [
                    {
                        "name": "dockerpty",
                        "source": "pip",
                        "version": "0.4.1"
                    }
                ],
                "docopt": [
                    {
                        "name": "docopt",
                        "source": "pip",
                        "version": "0.6.2"
                    }
                ],
                "python-dotenv": [
                    {
                        "name": "python-dotenv",
                        "source": "pip",
                        "version": "0.17.1"
                    }
                ],
                "texttable": [
                    {
                        "name": "texttable",
                        "source": "pip",
                        "version": "1.6.3"
                    }
                ],
                "websocket-client": [
                    {
                        "name": "websocket-client",
                        "source": "pip",
                        "version": "0.59.0"
                    }
                ]
            }
        }
    }
}
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.4

##### STEPS TO REPRODUCE

My task:
```yaml
  - name: Make sure compose service is up
    community.docker.docker_compose:
      project_src: /home/ansible/mid-server-stack
      files:
        - "/home/ansible/mid-server-stack/docker-compose_soc-midserver-dev.yml"
      state: present
```

##### EXPECTED RESULTS

Docker container is started

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1621002981.3259933-345140-106760538320042/AnsiballZ_docker_compose.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1621002981.3259933-345140-106760538320042/AnsiballZ_docker_compose.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1621002981.3259933-345140-106760538320042/AnsiballZ_docker_compose.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 1156, in <module>
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 1137, in main
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 665, in __init__
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 294, in __init__
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 394, in auth_params
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 180, in update_tls_hostname
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 392, in depr
  File "/tmp/ansible_community.docker.docker_compose_payload_jfzt1j_o/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 677, in deprecate
TypeError: deprecate() got an unexpected keyword argument 'date'
```

**Comment by felixfontein** [comment]
Please check out the requirements: https://github.com/ansible-collections/community.docker#tested-with-ansible

It explicitly says **Ansible versions before 2.9.10 are not supported.**.
