### ISSUE TITLE
Support for Docker Swarm Jobs

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.docker#28]
_From @alexanderadam on Apr 02, 2020 09:47_

##### SUMMARY

I'm not sure whether Ansible already has support for it but I found nothing so far.
I would be nice if Ansible would have support for [Docker Swarm Jobs](https://github.com/moby/moby/pull/40307). The Docker API seems to support this [since version v1.41](https://github.com/moby/moby/blob/master/docs/api/version-history.md#v141-api-changes).

##### ISSUE TYPE

* Support for Docker Swarm Jobs

##### ANSIBLE VERSION
2.9.6
##### COMPONENT NAME

docker_swarm_service

##### ADDITIONAL INFORMATION

I guess [Docker issue 23880](https://github.com/moby/moby/issues/23880) is better suited to give information about the what's and the why's.

_Copied from original issue: ansible/ansible#68629_

**Comment by frwickst** [comment]
This is also an issue for `docker_swarm_info`

The code is currently checking for only `Replicated` and `Global` as the modes for a service. These are however not the only modes that exists anymore, there is also `ReplicatedJob` and `GlobalJob`. When either of those types of services exists at the moment, then `docker_swarm_info` fails.

https://github.com/ansible-collections/community.docker/blob/d8548ef55fc719b1537b99570ea2d4960cd6ba06/plugins/modules/docker_swarm_info.py#L316

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_492jgky3/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 388, in <module>
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_492jgky3/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 376, in main
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_492jgky3/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 236, in __init__
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_492jgky3/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 273, in get_docker_items_list
KeyError: 'Mode'
```

Example of parial output from `docker service inspect` of `ReplicatedJob`:
```
[
    {
        "Spec": {
            "Mode": {
                  "ReplicatedJob": {
                      "MaxConcurrent": 1,
                      "TotalCompletions": 1
                  }
              },
        }
    }
]
```

**Comment by frwickst** [comment]
I strongly suggest adding the `bug` tag to this issue, as it is currently _preventing` running `docker_swarm_info` if there is a replicated job as the command will lead to a crash.

**Comment by felixfontein** [comment]
I moved the bug to #1002 and removed the label. This issue is about a feature.
