### ISSUE TITLE
docker compose: warn requires a string not a <class 'bytes'>

### ISSUE THREAD

**Issue by jurelou** [ansible-collections/community.docker#303]
##### SUMMARY
Error while running `docker-compose` tasks.

```
- name: Run compose
  community.docker.docker_compose:
    project_src: "/tmp/compose"
```

I got the following error:
```
TypeError: warn requires a string not a <class 'bytes'>
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- docker-compose

##### ANSIBLE VERSION
```
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION
```
Collection       Version
---------------- -------
community.docker 2.2.0 
```

##### CONFIGURATION
```
<blank>
```

##### OS / ENVIRONMENT
- Ubuntu20.04
- Alpine Linux v3.15

##### STEPS TO REPRODUCE

```yaml
- name: Run compose
  community.docker.docker_compose:
    project_src: "/tmp/compose"
```

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: warn requires a string not a <class 'bytes'>
fatal: [fak_home]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 833, in cmd_up\n  File \"/usr/lib/python3.9/site-packages/compose/project.py\", line 705, in up\n    raise ProjectError(\ncompose.project.ProjectError: Encountered errors while bringing up the project.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_compose', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_compose', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 1209, in <module>\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 1198, in main\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 707, in exec_module\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 837, in cmd_up\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py\", line 694, in fail\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py\", line 1538, in fail_json\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py\", line 1486, in _return_formatted\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py\", line 582, in warn\n  File \"/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/common/warnings.py\", line 18, in warn\n    return _formatwarnmsg_impl(msg)\nTypeError: warn requires a string not a <class 'bytes'>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by felixfontein** [comment]
The stack trace in readable form:
```
Traceback (most recent call last):
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 833, in cmd_up
  File "/usr/lib/python3.9/site-packages/compose/project.py", line 705, in up
    raise ProjectError(
compose.project.ProjectError: Encountered errors while bringing up the project.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1646766495.3228834-1531-24457562289793/AnsiballZ_docker_compose.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_compose', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_compose', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 1209, in <module>
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 1198, in main
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 707, in exec_module
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py", line 837, in cmd_up
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible_collections/community/docker/plugins/module_utils/common.py", line 694, in fail
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py", line 1538, in fail_json
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py", line 1486, in _return_formatted
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/basic.py", line 582, in warn
  File "/tmp/ansible_community.docker.docker_compose_payload_yfiibsbx/ansible_community.docker.docker_compose_payload.zip/ansible/module_utils/common/warnings.py", line 18, in warn
    return _formatwarnmsg_impl(msg)
TypeError: warn requires a string not a <class 'bytes'>
```

**Comment by felixfontein** [comment]
Hmm, I cannot reproduce this with Ubuntu 20.04 (#304). Which version of docker-compose are you using?

**Comment by felixfontein** [comment]
I also cannot reproduce it with Alpine 3.15 (now also in #304).

**Comment by jurelou** [comment]
I tried with docker-compose versions 1.28.0 and 1.29.2.
I downgraded the `community.docker` collection to 2.1.1 and it fixes the bug

**Comment by felixfontein** [comment]
That's really strange, since there was no code change for the docker_compose module between 2.1.1 and 2.2.0. In any case, I think I figured out what happened in your case, or at least parts of it - somehow docker-compose was emitting a warning next to an error, and the module screwed up while extracting the warning. #305 should fix that. There will still be the error that caused the failure, but I hope that now there will be better reporting of what caused it.

**Comment by jurelou** [comment]
Thanks for the fix. I will retry and come back to you with more information.

**Comment by felixfontein** [comment]
@jurelou now that a new release of this collection (and of Ansible) is out with #305 included, could you check what happens now?

**Comment by jurelou** [comment]
I tried with `ansible-core==2.12.1` and `community.docker 2.2.1` and couldn't reproduce the bug.

**Comment by felixfontein** [comment]
Thanks for checking!
