### ISSUE TITLE
docker_swarm_info: KeyError: 'EndpointSpec'

### ISSUE THREAD

**Issue by benformosa** [ansible-collections/community.docker#636]
##### SUMMARY
This issue from the old builtin version is present in this repo:
https://github.com/ansible/ansible/issues/67956

> While executing task with docker_swarm_info module and `service` property with value `yes` I get an error KeyError: 'EndpointSpec'

I have the same problem in community.docker 3.4.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm_info.py

##### ANSIBLE VERSION

```
ansible [core 2.13.6]
  config file = /home/BF2675_a/.ansible.cfg
  configured module search path = ['/home/BF2675_a/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/BF2675_a/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 3.4.6
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/git/ansible/inventory.ini']
GALAXY_SERVER_LIST(/home/user/.ansible.cfg) = ['published_repo', 'rh-certified_repo', 'community_repo']
```

##### OS / ENVIRONMENT

RHEL 8.7

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  tasks:
    - community.docker.docker_swarm_info:
        services: true
      become: true
```

##### EXPECTED RESULTS

Task runs successfully

##### ACTUAL RESULTS

```paste below
$ ansible-playbook repro.yml -l target.example.com

PLAY [all] *****************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
ok: [target.example.com]

TASK [community.docker.docker_swarm_info] **********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'EndpointSpec'
fatal: [target.example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to target.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py\", line 388, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py\", line 376, in main\r\n  File \"/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py\", line 236, in __init__\r\n  File \"/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py\", line 272, in get_docker_items_list\r\n  File \"/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py\", line 329, in get_essential_facts_services\r\nKeyError: 'EndpointSpec'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************
target.example.com : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by felixfontein** [comment]
The traceback in readable form:
```
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1685066155.4181426-569870-162543682350861/AnsiballZ_docker_swarm_info.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 388, in <module>
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 376, in main
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 236, in __init__
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 272, in get_docker_items_list
  File "/tmp/ansible_community.docker.docker_swarm_info_payload_llgboc5i/ansible_community.docker.docker_swarm_info_payload.zip/ansible_collections/community/docker/plugins/modules/docker_swarm_info.py", line 329, in get_essential_facts_services
KeyError: 'EndpointSpec'
```

**Comment by felixfontein** [comment]
There was a fix for this in the old repo (https://github.com/ansible/ansible/pull/67957/files), but apparently nobody migrated it to the new collection repo(s)...

**Comment by felixfontein** [comment]
I re-created that PR in #637.
