### ISSUE TITLE
Sanitize error message when `docker compose version` returns not supported version format

### ISSUE THREAD

**Issue by koutoftimer** [ansible-collections/community.docker#825]
# Issue

Currently (2024-03-27) Arch repo contains version of `docker compose` which reports its version as "dev" instead of something like "2.26.0", which causes 

```
$ pacman -Q docker-compose
docker-compose 2.26.0-1
```

```
$ docker compose version
Docker Compose version dev
```

```
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose_v2.py", line 638, in <module>
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose_v2.py", line 631, in main
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose_v2.py", line 419, in __init__
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible_collections/community/docker/plugins/module_utils/compose_v2.py", line 521, in __init__
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible/module_utils/compat/version.py", line 60, in __lt__
  File "/tmp/ansible_community.docker.docker_compose_v2_payload_9tu8jd7j/ansible_community.docker.docker_compose_v2_payload.zip/ansible/module_utils/compat/version.py", line 338, in _cmp
TypeError: '<' not supported between instances of 'str' and 'int'
```

when using module

```
- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ project_src }}"
    project_name: accounts
    state: absent
```

Affected version:

`$ ansible-galaxy collection install community.docker:3.8.1` 

# Feature 

Respond with proper error message.

**Comment by felixfontein** [comment]
This looks like a packaging error in Arch. You should report it as a bug to Arch and stick to an earlier version of Docker Compose until it gets fixed.

We need the correct version to determine the behavior of the module.

**Comment by koutoftimer** [comment]
@felixfontein this is why it is feature request, not bug fix.

**Comment by iamwacko** [comment]
> This looks like a packaging error in Arch. You should report it as a bug to Arch and stick to an earlier version of Docker Compose until it gets fixed.
> 
> We need the correct version to determine the behavior of the module.

https://gitlab.archlinux.org/archlinux/packaging/packages/docker-compose/-/issues/1

The issue is now reported to Arch

**Comment by felixfontein** [comment]
Thanks for reporting it! (I also can confirm that the previous Compose release on Arch did output the version correctly, it's only the latest one that outputs `dev` instead.)

**Comment by iamwacko** [comment]
Christian Heusel fixed the Arch error.

Might still be a good idea to have a specific error for version weirdness.

**Comment by felixfontein** [comment]
`dev` is the default string that's used when the version isn't set: https://github.com/docker/compose/blob/main/internal/variables.go#L21. Self-built versions using the build process in the project's Makefile usually have versions like `v2.26.0-5-g6fe69b25`, but the Arch build isn't using that build mechanism (for other reasons).

**Comment by felixfontein** [comment]
#826 improves the error message.
