### ISSUE TITLE
Issue with community.docker API with older version of Ansible

### ISSUE THREAD

**Issue by GalletFlorian** [ansible-collections/community.docker#958]
##### SUMMARY
Hello, 

Recently, the community.docker collection API stopped working with older version of ansible.

Starting galaxy collection install process
Process install dependency map
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.docker: '/api/v3/plugin/ansible/content/published/collections/index/c
ommunity/docker/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/docker/versions/'
to see the full traceback, use -vvv
The command '/bin/sh -c ansible-galaxy collection install community.docker' returned a non-zero code: 250

It appears, most likely, during this summer.

The problematic command is `ansible-galaxy collection install community.docker`

Note that the issue is not present if .e.g. I use ubuntu:focal and ansible==6.7.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ubuntu  18.04 / Bionic docker image
Python 2.7
Ansible 4.9.0

##### ANSIBLE VERSION
```
ansible [core 2.11.12] 
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Mar  8 2023, 18:40:28) [GCC 7.5.0]
  jinja version = 2.11.3
  libyaml = True

```

##### COLLECTION VERSION
N/A

##### CONFIGURATION

```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the 
controller starting with Ansible 2.12. Current version: 2.7.17 (default, Mar  8
 2023, 18:40:28) [GCC 7.5.0]. This feature will be removed from ansible-core in
 version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

```

##### OS / ENVIRONMENT
Ubuntu 18.04 / Bionic docker image

##### STEPS TO REPRODUCE
Create a dockefile with

```dockerfile
FROM ubuntu:bionic
RUN apt update && \
		apt install -y software-properties-common && \
		apt-add-repository -y --update ppa:ansible/ansible && \
		apt install -y openssh-server iproute2 python-pip
RUN pip install ansible==4.9.0 docker==4.4.4 jmespath==0.10.0 pyrsistent==0.16.1 docker-compose==1.26.2 pyyaml==5.4.1
RUN ansible-galaxy collection install community.docker
```

Run the dockerfile with

`docker build .`

##### EXPECTED RESULTS
The build of the dockerfile ends correctly

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the 
controller starting with Ansible 2.12. Current version: 2.7.17 (default, Mar  8
 2023, 18:40:28) [GCC 7.5.0]. This feature will be removed from ansible-core in
 version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ansible-galaxy [core 2.11.12] 
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 2.7.17 (default, Mar  8 2023, 18:40:28) [GCC 7.5.0]
  jinja version = 2.11.3
  libyaml = True
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map
Created /root/.ansible/galaxy_token
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.docker: '/api/v3/plugin/ansible/content/published/collections/index/c
ommunity/docker/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/docker/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 135, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 552, in run
    return context.CLIARGS['func']()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 75, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 1188, in execute_install
    artifacts_manager=artifacts_manager,
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 1217, in _execute_install_collection
    artifacts_manager=artifacts_manager,
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/collection/__init__.py", line 554, in install_collections
    upgrade=upgrade,
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/collection/__init__.py", line 1365, in _resolve_depenency_map
    max_rounds=2000000,  # NOTE: same constant pip uses
  File "/usr/local/lib/python2.7/dist-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python2.7/dist-packages/resolvelib/resolvers.py", line 319, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/lib/python2.7/dist-packages/resolvelib/resolvers.py", line 176, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/local/lib/python2.7/dist-packages/resolvelib/resolvers.py", line 79, in from_requirement
    matches = provider.find_matches(requirements=[requirement])
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/dependency_resolution/providers.py", line 214, in find_matches
    coll_versions = self._api_proxy.get_collection_versions(first_req)
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 104, in get_collection_versions
    requirement,
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 102, in <genexpr>
    (version, api)
  File "/usr/local/lib/python2.7/dist-packages/ansible/galaxy/collection/galaxy_api_proxy.py", line 82, in _get_collection_versions
    raise last_error
KeyError: '/api/v3/plugin/ansible/content/published/collections/index/community/docker/versions/'
The command '/bin/sh -c ansible-galaxy collection install community.docker -vvv' returned a non-zero code: 250

```

**Comment by felixfontein** [comment]
This has nothing to do with community.docker, but with Ansible Galaxy and your version of ansible-core.

You are using an unsupported version of Ansible that has been End of Life for over 1.5 years by now (https://docs.ansible.com/ansible-core/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix). Since the migration of Ansible Galaxy to the new codebase at the end of last year some older, unsupported versions of ansible-core can no longer talk to Galaxy.

If you need support with Galaxy, please ask on the [Ansible forum](https://forum.ansible.com/). Thanks.
